services:
  NerdySouth\StripeBundle\Service\PaymentService:
    arguments:
      $stripeSecretKey: '%nerdysouth_stripe.api_key%'
      $entityManager: Doctrine\ORM\EntityManagerInterface
  NerdySouth\StripeBundle\Controller\StripeWebhookController:
    arguments:
      $stripeWebhookSecret: '%nerdysouth_stripe.webhook_secret%'
      $dispatcher: Symfony\Contracts\EventDispatcher\EventDispatcherInterface
      $entityManager: Doctrine\ORM\EntityManagerInterface