services:
  NerdySouth\StripeBundle\Service\PaymentService:
    arguments:
      $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'

  NerdySouth\StripeBundle\Controller\StripeWebhookController:
    public: true
    arguments:
      $stripeWebhookSecret: '%env(STRIPE_WEBHOOK_SECRET)%'