services:
  NerdySouth\StripeBundle\Service\PaymentService:
    arguments:
      $stripeSecretKey: '%nerdysouth_stripe.api_key%'
      $entityManager: '@doctrine.orm.entity_manager'

  NerdySouth\StripeBundle\Controller\StripeWebhookController:
    arguments:
      $stripeWebhookSecret: '%nerdysouth_stripe.webhook_secret%'
      $dispatcher: '@event_dispatcher'
      $entityManager: '@doctrine.orm.entity_manager'